Repository github/automatic-contrib-prs, pull requests merged in 2024-05, with the labels that each got.

#62 chore: add OSSF scorecard github action and README badge
  .github/workflows/auto-labeler.yml
  .github/workflows/codeql.yml
  .github/workflows/docker-image.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yml
  README.md
Labels: maintenance

#67 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/docker-image.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yml
Labels: maintenance, release

#70 chore: delete unneeded custom codeql GitHub Action
  .github/workflows/codeql.yml
Labels: maintenance

#72 chore: Switch to weekly dep updates to reduce noise
  .github/dependabot.yml
Labels: maintenance

#80 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
  README.md
Labels: maintenance

#81 ci: Add Jeff to review new data releases
  .github/pull_request_template.md
Labels: automation
